name: KoMQoM
favicon: null
layout_spectrum: 0.41641196119599044
typography_spectrum: 0.07384643517434597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.34472728008404374
  lightness: 0.20907442248426378
  saturation: 0.2617203670088202
  rhythmicContrast: 0.445010346127674
purpose: []
